// Menü-Daten (je Kategorie mind. 10 Artikel)
(function () {
  const vorspeisen = [
    {
      id: "v1",
      title: "Mini Frühlingsrollen (6 St.)",
      desc: "Gemüsefüllung",
      cents: 499,
      img: "./assets/img/mini-fruehlingsrollen.webp",
    },
    {
      id: "v2",
      title: "Banh Phong Tom",
      desc: "Krabbenchips",
      cents: 350,
      img: "./assets/img/banh-phong-tom.webp",
    },
    {
      id: "v3",
      title: "Sommerrollen (2 St.)",
      desc: "Hähnchen & Kräuter",
      cents: 520,
      img: "./assets/img/sommerrollen.webp",
    },
    {
      id: "v4",
      title: "Gedämpfte Dumplings",
      desc: "3 Stück, Schwein",
      cents: 480,
      img: "./assets/img/dumplings.webp",
    },
    {
      id: "v5",
      title: "Edamame",
      desc: "Salz & Limette",
      cents: 320,
      img: "./assets/img/edamame.webp",
    },
    {
      id: "v6",
      title: "Pikante Tintenfischringe",
      desc: "Knusprig",
      cents: 590,
      img: "./assets/img/tintenfisch.webp",
    },
    {
      id: "v7",
      title: "Tofu-Spiesschen",
      desc: "hausgemachte Sauce",
      cents: 430,
      img: "./assets/img/tofu.webp",
    },
    {
      id: "v8",
      title: "Gyoza (5 St.)",
      desc: "mit Dip",
      cents: 450,
      img: "./assets/img/gyoza.webp",
    },
    {
      id: "v9",
      title: "Vietnamesische Frühlingsrollen",
      desc: "vegetarisch",
      cents: 470,
      img: "./assets/img/vn-rolls.webp",
    },
    {
      id: "v10",
      title: "Sesam-Hähnchen Bites",
      desc: "süß-sauer",
      cents: 550,
      img: "./assets/img/sesam-huhn.webp",
    },
  ];

  const suppen = [
    {
      id: "s1",
      title: "Pho Bo",
      desc: "Rindfleisch, Reisnudeln",
      cents: 990,
      img: "./assets/img/pho-bo.webp",
    },
    {
      id: "s2",
      title: "Tom Yum",
      desc: "scharfe Garnelensuppe",
      cents: 1090,
      img: "./assets/img/tom-yum.webp",
    },
    {
      id: "s3",
      title: "Miso Suppe",
      desc: "Tofu, Wakame",
      cents: 420,
      img: "./assets/img/miso.webp",
    },
    {
      id: "s4",
      title: "Sauer-Scharf Suppe",
      desc: "asiatisch gewürzt",
      cents: 750,
      img: "./assets/img/sauer-scharf.webp",
    },
    {
      id: "s5",
      title: "Hühnersuppe mit Glasnudeln",
      desc: "hausgemacht",
      cents: 850,
      img: "./assets/img/huehnersuppe.webp",
    },
    {
      id: "s6",
      title: "Süßkartoffel-Kokos-Suppe",
      desc: "cremig",
      cents: 720,
      img: "./assets/img/kokos-suppe.webp",
    },
    {
      id: "s7",
      title: "Ramen Shoyu",
      desc: "Schweinebrühe",
      cents: 1090,
      img: "./assets/img/ramen.webp",
    },
    {
      id: "s8",
      title: "Ente-Suppe",
      desc: "asiatisch mariniert",
      cents: 1190,
      img: "./assets/img/ente-suppe.webp",
    },
    {
      id: "s9",
      title: "Kokos-Limetten Suppe",
      desc: "mild",
      cents: 680,
      img: "./assets/img/kokos-limette.webp",
    },
    {
      id: "s10",
      title: "Pilzcremesuppe",
      desc: "mit Kräutern",
      cents: 490,
      img: "./assets/img/pilzcreme.webp",
    },
  ];

  const salate = [
    {
      id: "sal1",
      title: "Gurken-Avocado Salat",
      desc: "sesam-dressing",
      cents: 550,
      img: "./assets/img/gurken-salat.webp",
    },
    {
      id: "sal2",
      title: "Papaya Salat",
      desc: "scharf",
      cents: 620,
      img: "./assets/img/papaya-salat.webp",
    },
    {
      id: "sal3",
      title: "Mango-Salat",
      desc: "fruchtig",
      cents: 640,
      img: "./assets/img/mango-salat.webp",
    },
    {
      id: "sal4",
      title: "Thunfisch Tataki Salat",
      desc: "zart",
      cents: 980,
      img: "./assets/img/tataki.webp",
    },
    {
      id: "sal5",
      title: "Edamame-Salat",
      desc: "leicht",
      cents: 520,
      img: "./assets/img/edamame-salat.webp",
    },
    {
      id: "sal6",
      title: "Kohl-Sesam Salat",
      desc: "knackig",
      cents: 480,
      img: "./assets/img/kohl-salat.webp",
    },
    {
      id: "sal7",
      title: "Glasnudel Salat",
      desc: "mit Garnelen",
      cents: 890,
      img: "./assets/img/glasnudel.webp",
    },
    {
      id: "sal8",
      title: "Tofu Salat",
      desc: "vegan",
      cents: 620,
      img: "./assets/img/tofu-salat.webp",
    },
    {
      id: "sal9",
      title: "Sesam-Rind Salat",
      desc: "kräftig",
      cents: 1020,
      img: "./assets/img/rind-salat.webp",
    },
    {
      id: "sal10",
      title: "Garnelen-Salat",
      desc: "leicht mariniert",
      cents: 980,
      img: "./assets/img/garnelen-salat.webp",
    },
  ];

  const sushiMaki = [
    {
      id: "su1",
      title: "California Roll (8 St.)",
      desc: "Avocado, Surimi",
      cents: 899,
      img: "./assets/img/california.webp",
    },
    {
      id: "su2",
      title: "Lachs Maki (8 St.)",
      desc: "frischer Lachs",
      cents: 1099,
      img: "./assets/img/lachs-maki.webp",
    },
    {
      id: "su3",
      title: "Thunfisch Roll",
      desc: "pikant",
      cents: 1149,
      img: "./assets/img/thunfisch.webp",
    },
    {
      id: "su4",
      title: "Veggie Roll",
      desc: "Gemüse, Tofu",
      cents: 799,
      img: "./assets/img/veggie-roll.webp",
    },
    {
      id: "su5",
      title: "Ebi Tempura Roll",
      desc: "knusprig",
      cents: 1199,
      img: "./assets/img/ebi-tempura.webp",
    },
    {
      id: "su6",
      title: "Unagi Roll",
      desc: "Aal, süße Sauce",
      cents: 1299,
      img: "./assets/img/unagi.webp",
    },
    {
      id: "su7",
      title: "Spicy Tuna Roll",
      desc: "scharf",
      cents: 1199,
      img: "./assets/img/spicy-tuna.webp",
    },
    {
      id: "su8",
      title: "Philadelphia Roll",
      desc: "Lachs & Frischkäse",
      cents: 1099,
      img: "./assets/img/philadelphia.webp",
    },
    {
      id: "su9",
      title: "Dragon Roll",
      desc: "Aal & Avocado",
      cents: 1399,
      img: "./assets/img/dragon.webp",
    },
    {
      id: "su10",
      title: "Rainbow Roll",
      desc: "gemischter Belag",
      cents: 1499,
      img: "./assets/img/rainbow.webp",
    },
  ];

  const desserts = [
    {
      id: "d1",
      title: "Mochi Eis (3 St.)",
      desc: "versch. Sorten",
      cents: 399,
      img: "./assets/img/mochi.webp",
    },
    {
      id: "d2",
      title: "Matcha Pudding",
      desc: "cremig",
      cents: 450,
      img: "./assets/img/matcha.webp",
    },
    {
      id: "d3",
      title: "Sesam Kugeln",
      desc: "frittiert",
      cents: 350,
      img: "./assets/img/sesam-kugeln.webp",
    },
    {
      id: "d4",
      title: "Gebratene Banane",
      desc: "mit Honig",
      cents: 420,
      img: "./assets/img/banane.webp",
    },
    {
      id: "d5",
      title: "Milchreis mit Mango",
      desc: "süß",
      cents: 480,
      img: "./assets/img/milchreis.webp",
    },
    {
      id: "d6",
      title: "Klebreisbällchen",
      desc: "traditionell",
      cents: 390,
      img: "./assets/img/klebreis.webp",
    },
    {
      id: "d7",
      title: "Ingwer-Eis",
      desc: "erfrischend",
      cents: 360,
      img: "./assets/img/ingwer-eis.webp",
    },
    {
      id: "d8",
      title: "Tee Creme Brûlée",
      desc: "asiatische Note",
      cents: 520,
      img: "./assets/img/creme-brulee.webp",
    },
    {
      id: "d9",
      title: "Pandan Pudding",
      desc: "duftig",
      cents: 430,
      img: "./assets/img/pandan.webp",
    },
    {
      id: "d10",
      title: "Fruchtsalat",
      desc: "saisonal",
      cents: 380,
      img: "./assets/img/fruchtsalat.webp",
    },
  ];

  const getraenke = [
    {
      id: "g1",
      title: "Coca-Cola 0,33l",
      desc: "",
      cents: 249,
      img: "./assets/img/coke.webp",
    },
    {
      id: "g2",
      title: "Mineralwasser 0,5l",
      desc: "still",
      cents: 199,
      img: "./assets/img/wasser.webp",
    },
    {
      id: "g3",
      title: "Green Tea",
      desc: "warm",
      cents: 199,
      img: "./assets/img/green-tea.webp",
    },
    {
      id: "g4",
      title: "Eistee Pfirsich",
      desc: "kalt",
      cents: 249,
      img: "./assets/img/istee.webp",
    },
    {
      id: "g5",
      title: "Asiatisches Bier 0,33l",
      desc: "kühl",
      cents: 349,
      img: "./assets/img/bier.webp",
    },
    {
      id: "g6",
      title: "Sake 200ml",
      desc: "warm oder kalt",
      cents: 599,
      img: "./assets/img/sake.webp",
    },
    {
      id: "g7",
      title: "Mango Lassi",
      desc: "cremig",
      cents: 399,
      img: "./assets/img/mango-lassi.webp",
    },
    {
      id: "g8",
      title: "Ingwer-Limonade",
      desc: "hausgemacht",
      cents: 299,
      img: "./assets/img/ginger.webp",
    },
    {
      id: "g9",
      title: "Kaffee",
      desc: "schwarz",
      cents: 199,
      img: "./assets/img/kaffee.webp",
    },
    {
      id: "g10",
      title: "Grüner Smoothie",
      desc: "gesund",
      cents: 449,
      img: "./assets/img/smoothie.webp",
    },
  ];

  window.MENU_DATA = {
    vorspeisen,
    suppen,
    salate,
    sushiMaki,
    desserts,
    getraenke,
  };
})();
